### ISSUE TITLE
Missing required client configuration options

### ISSUE THREAD

**Issue by ndessenius** [bhutanio/imagehost#1]
Hello,
I got some error when i try to use your app.

> InvalidArgumentException in ClientResolver.php line 364:
Missing required client configuration options: 

or

> Missing required client configuration options:
C:\laragon\www\album\vendor\aws\aws-sdk-php\src\ClientResolver.php#364

It occurs when i try to get 'My uploads' or even when i try to upload some images.
I'm running Laravel 5.4.
Do you know what did i forget to configure ? I don't want to use S3 or whatever.

**Comment by abixalmon** [comment]
I have updated the README.MD file with detailed setup instruction

**Comment by ndessenius** [comment]
Thank you so much and congrats for your app!
